##################
### FILE PATHS ###
##################
# experiment directory
model_dir: exp_deeplab_v4

data_path: 0.0_test_data

# Input data for the model
ortho_image: amazon_mc_input_data/orthoimage/NOV_2017_FINAL_004.tif
train_segmentation_path: "amazon_mc_input_data/segmentation/train_set.tif"
test_segmentation_path: "amazon_mc_input_data/segmentation/test_set.tif"

mask_path: "amazon_mc_input_data/mask.tif"


checkpoint_file: checkpoint.pth.tar

# Num of iter
num_iter : 1

# pred2raster parameters
# samples per epoch
overlap: [0.1, 0.3, 0.5]

# num samples per epoch
samples: 100
# True for data augmentation during training
augment: True

# convnet architecture --> 'resunet','deeplabv3_resnet50',deeplabv3+_resnet9, deeplabv3+
arch: deeplabv3_resnet50
# True for load pretrained weights from Imagenet
is_pretrained: True

# True for frozen the resnet backbone
# frozen: False
# Filter for the ResUnet for trained from scratch
filters: [32, 32, 32, 32]

### optim parameters ###
# number of total epochs to run
epochs: 2
# batch size per gpu, i.e. how many unique instances per gpu
batch_size: 16
# base learning rate
base_lr: 0.01
# final learning rate
final_lr: 0.0001
# number of warmup epochs
warmup_epochs: 5
# initial warmup learning rate
start_warmup: 0.0

# weight decay
weight_decay: 1e-06


### others parameters ###
# number of data loading workers
workers: 0
# random seed
seed: 31


###############################
#### Evaluation parameters ####
###############################

# True for training 4 disjoint regions
size_crops: 128
# Número de classes
nb_class: 14
