arch: deeplabv3_resnet50
augment: true
base_lr: 0.01
batch_size: 16
checkpoint_file: checkpoint.pth.tar
data_path: 0.0_test_data
depth_thr: 0.2
dropout_rate: 0.01
epochs: 2
filters:
- 32
- 32
- 32
- 32
final_lr: 0.0001
is_pretrained: true
lambda_weight: 1
mask_path: amazon_mc_input_data/mask.tif
model_dir: exp_deeplab_v4
nb_class: 17
num_iter: 2
ortho_image: amazon_mc_input_data/orthoimage/NOV_2017_FINAL_004.tif
overlap:
- 0.1
- 0.3
- 0.5
prob_thr: 0.7
samples: 100
seed: 31
size_crops: 128
start_warmup: 0.0
test_segmentation_path: amazon_mc_input_data/segmentation/test_set.tif
train_segmentation_path: amazon_mc_input_data/segmentation/train_set.tif
warmup_epochs: 5
weight_decay: 1.0e-06
workers: 0
